name: Tests

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
  merge_group:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: neuroinformatics-unit/actions/lint@v3

  test:
    needs: [linting]
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Run all supported Python versions on linux
        python-version: ["3.12", "3.13", "3.14"]
        os: [ubuntu-latest]
        # Include 1 MacOS Silicon (latest) and 1 Windows run
        include:
        - os: macos-latest
          python-version: "3.14"
        - os: windows-latest
          python-version: "3.14"

    steps:
      # these libraries enable testing on Qt on linux
      - uses: pyvista/setup-headless-display-action@c103a2ff45650d38cb71684b5dc6cdfeb9442c79 # v5.1.0
        with:
          qt: true
      - name: Cache Test Data
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.movement/*
          key: cached-test-data-${{ runner.os }}
          restore-keys: cached-test-data
      - uses: neuroinformatics-unit/actions/test@v3
        with:
          python-version: ${{ matrix.python-version }}
          secret-codecov-token: ${{ secrets.CODECOV_TOKEN }}

  build_sdist_wheels:
    name: Build source distribution
    needs: [test]
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
    - uses: neuroinformatics-unit/actions/build_sdist_wheels@v3


  upload_all:
    name: Publish build distributions
    needs: [build_sdist_wheels]
    if: github.event_name == 'push' && github.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment: # use Trusted Publisher route
      name: pypi
      url: https://pypi.org/p/movement
    permissions:
      id-token: write # mandatory for trusted publishing
    steps:
    - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: artifact
        path: dist
    - uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33 # v1.14.2
